import CartIcon from '../../public/svg/cart.svg'
import UserIcon from '../../public/svg/user.svg'
import SearchIcon from '../../public/svg/search.svg'
import DownIcon from '../../public/svg/down.svg'
import DeliveryIcon from '../../public/svg/delivery.svg'
import PhoneIcon from '../../public/svg/phone.svg'
import LeftIcon from '../../public/svg/left.svg'
import RigthIcon from '../../public/svg/right.svg'
import ListIcon from '../../public/svg/list.svg'
import CloseIcon from '../../public/svg/close.svg'
import AddIcon from '../../public/svg/add.svg'
export const Icons = { AddIcon, CloseIcon, ListIcon, CartIcon, UserIcon, SearchIcon, DownIcon, DeliveryIcon, PhoneIcon, LeftIcon, RigthIcon}